# Generated by Django 5.2.dev20240913145207 on 2024-09-23 16:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='WorkBoard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('status', models.CharField(choices=[('ToDo', 'ToDo'), ('In Progress', 'In Progress'), ('Completed', 'Completed')], default='ToDo', max_length=20)),
                ('order', models.PositiveIntegerField(default=0)),
                ('workboard', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tasks', to='workboards.workboard')),
            ],
            options={
                'ordering': ['order'],
            },
        ),
    ]
